mind/blueprints/mind.py
from flask import (
    Blueprint, render_template, redirect, url_for, request,
    abort, flash, send_from_directory, session, jsonify, current_app
)
from flask_login import login_required, current_user

from mind.models import Question, Answer, User
from mind.app import db, google, LoginUser

mind = Blueprint('mind', __name__)


@mind.route('')
def index():
    question_slug = 'how-are-you-today'
    question_url = url_for('.show_question',
                           question=question_slug)
    return redirect(question_url), 302


@mind.route('/info')
def info():
    return jsonify(
        headers=dict(request.headers),
        session=dict(session)
    ), 200


@mind.route('/login')
def login():
    if current_app.config['ENVIRONMENT'] == 'dev':
        user = User.get_or_create('example@example.org')
        LoginUser.login(user, {
            'email': 'example@example.org',
            'given_name': 'Example',
        })
        return redirect(url_for('.index')), 302

    callback = url_for('.authorized', _external=True, _scheme='https')
    return google.authorize(callback=callback)


@mind.route('/logout')
def logout():
    session.pop('google_token', None)
    LoginUser.logout()
    flash('Logged out')
    return redirect(url_for('.index'))


@mind.route('/oauth2-callback')
def authorized():
    resp = google.authorized_response()
    if resp is None:
        return ('Access denied: ' +
                'reason={error_reason[0]} ' +
                'error={error_description[0]}').format(**request.args), 401

    session['google_token'] = (resp['access_token'], '')
    me = google.get('userinfo')
    user = User.get_or_create(me.data['email'])
    LoginUser.login(user, me.data)

    return redirect(url_for('.index')), 302


@google.tokengetter
def get_google_oauth_token():
    return session.get('google_token')


@mind.route('/static/<path:path>')
def static(path):
    return send_from_directory('static', path)


@mind.route('/settings')
@login_required
def show_settings():
    return render_template('show_settings.html')


@mind.route('/settings', methods=['POST'])
@login_required
def update_settings():
    current_user.user.twitter_handle = request.form['twitter_handle']
    db.session.add(current_user.user)
    db.session.commit()

    flash('Settings updated')

    return redirect(url_for('.show_settings')), 302


# Question related routes
@mind.route('/question', methods=['GET'])
def list_questions():
    questions = Question.query.all()

    return render_template('list_questions.html',
                           questions=questions)


@mind.route('/question', methods=['POST'])
def add_question():
    db.session.add(Question(title=request.form['question_title']))
    db.session.commit()

    return redirect(url_for('.list_questions'))


@mind.route('/question/<question>', methods=['GET'])
def show_question(question):
    return render_template('show_question.html',
                           question=question)


@mind.route('/question/<question>/answer', methods=['POST'])
@login_required
def add_answer(question):
    answer = Answer(
        question_id=question.id,
        answer=request.form['answer'],
        user=current_user.user
    )
    db.session.add(answer)
    db.session.commit()

    flash('Answer added')
    return redirect(url_for('.show_question', question=question))


def rangerer(start, end, step):
    while start <= end:
        yield start
        start += step


@mind.route('/question/<question>/stats', methods=['GET'])
@login_required
def show_question_stats(question):
    user = current_user.user

    return render_template('show_question_stats.html',
                           question=question,
                           stats=question.stats_for_user(user))


MODEL_URL_MAP = {
    'question': Question
}


@mind.url_defaults
def add_slug_to_url(endpoint, values):
    for field in MODEL_URL_MAP.keys():
        if field in values and hasattr(values[field], 'slug'):
            values[field] = values[field].slug


@mind.url_value_preprocessor
def resolve_slug(endpoint, values):
    for field, model in MODEL_URL_MAP.items():
        if field in values:
            record = model.query \
                    .filter_by(slug=values[field]) \
                    .one_or_none()
            if not record:
                abort(404)
            values[field] = record

mind/templates/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <!--Import Google Icon Font-->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link type="text/css" rel="stylesheet" href="{{ url_for('mind.static', path='materialize/css/materialize.css' ) }}"  media="screen,projection"/>
  <link type="text/css" rel="stylesheet" href="{{ url_for('mind.static', path='css/main.css') }}"/>

  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body>
  {% include "partials/navigation.html" %}

  <div class="section no-pad-bot">
    <div class="container">
      {% block main %}{% endblock %}
    </div>
  </div>
  <!--Import jQuery before materialize.js-->
  <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
  <script src="{{ url_for('mind.static', path='materialize/js/materialize.js') }}"></script>
  <script src="{{ url_for('mind.static', path='js/init.js') }}"></script>
</body>
</html>

mind/templates/index.html
{% extends "_base.html" %}

{% block main %}
<a href="{{ url_for(".list_questions") }}">List questions</a>
{% endblock %}

mind/templates/list_questions.html
{% extends "_base.html" %}

{% block main %}
<ul>
  {% for question in questions %}
  <li><a href="{{ url_for(".show_question", question=question) }}">{{ question.title }}</a></li>
  {% endfor %}
</ul>
{% endblock %}

mind/templates/show_question.html
{% extends "_base.html" %}

{% block main %}
{% if current_user.is_authenticated %}
<p>Hi {{ current_user.given_name }}</p>
{% endif %}
<h1>{{ question.title }}</h1>

{% with messages = get_flashed_messages() %}
{% if messages %}
<p class="flash">{{ messages[0] }}</p>
{% endif %}
{% endwith %}

{% if current_user.is_authenticated %}
<p>
  <form id=answer-form method=post action="{{ url_for(".add_answer", question=question) }}">
    <input type=hidden name=answer value="">
  </form>
  {% for n in range(1, 6) %}
  <a data-answer="{{ n }}" class="answer btn-floating btn-large waves-effect waves-light teal">{{ n }}</a>
  {% endfor %}
</p>
<a href="{{ url_for('.show_question_stats', question=question) }}">show stats</a>
{% else %}
<a href="{{ url_for('.login') }}">login to answer</a>
{% endif %}
{% endblock %}

mind/templates/show_question_stats.html
{% extends "_base.html" %}

{% block main %}
  <canvas id="myChart" width="400" height="200"></canvas>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.13.0/moment.min.js"></script>
  <script src="{{ url_for('mind.static', path='js/Chart.min.js') }}"></script>
  <script>
    var timeFormat = 'MM/DD/YYYY';
    var ctx = document.getElementById("myChart");
    var myChart = new Chart(ctx, {
				type: 'bar',
						data: {
                labels: [
                  {% for key, _ in stats %}
                    "{{ key.strftime('%Y-%m-%d') }}",
                  {% endfor %}
                  ],
								datasets: [{
                  data: [
                    {% for _, value in stats %}
                    {{ value or 'null' }},
                    {% endfor %}
                  ],
										borderWidth: 1
								}]
						},
						options: {
								scales: {
                    xAxes: [{
                      type: "time",
                      time: {
                        unit: 'day'
                      },
                      scaleLabel: {
                        display: true,
                        labelString: "Date"
                      }
                    }],
										yAxes: [{
												ticks: {
														beginAtZero:true
												}
										}]
								}
						}
				});
  </script>
{% endblock %}

mind/templates/show_settings.html
{% extends "_base.html" %}

{% block main %}
<h1>Settings</h1>

{% with messages = get_flashed_messages() %}
{% if messages %}
<p class="flash">{{ messages[0] }}</p>
{% endif %}
{% endwith %}

<form id=settings-form method=post action="{{ url_for('.update_settings') }}">
  <div class="input-field">
    <input id=settings-twitter-handle name=twitter_handle type=text value="{{ current_user.user.twitter_handle or '' }}">
    <label for=settings-twitter-handle>Twitter handle</label>
  </div>
  <input type=submit class="btn" value="Update settings">
</form>
{% endblock %}